namespace OpenTibia.Common.Structures
{
    public enum FeatureFlag
    {
        LookTypeUInt16,
        MessageStatement,
        LoginPacketEncryption,
        PlayerAddons,
        PlayerStamina,
        NewFluids,
        MessageLevel,
        PlayerSpecialConditionUInt16,
        NewOutfitProtocol,
        ReadableItemDate,
        QuestLog,
        NpcsChannel,
        ProtocolChecksum,
        AccountString,
        PlayerCapacityUInt32,
        PartyChannel,
        ChallengeOnLogin,
        TileIndex,        
        CreatureWarIcon,
        CreatureBlock,
        AttackSequence,
        RuleViolationChannel,
        GamemasterChannel,
        PenalityOnDeath,
        PlayerExperienceUInt64,
        PlayerMounts,
        SpellList
    }
}